### ISSUE TITLE
UiVeeInput is bugged, Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by Type-32** [BayBreezy/ui-thing#24]
If I remove UiVeeInput, everything's fine; if I add it in, it just gives me those errors.

On top of this error, I think the documentation regarding forms and vee validate has some consistency issues. For example, the "Form" page contains code that reports errors on the Form tag adn Field Tag when i copy and paste it fully. The "Login" page example uses a different form validator (yup instead of zod) than the demonstration examples.

My code:
```vue
<template>
    <div class="flex h-screen items-center justify-center">
        <div class="w-full max-w-[330px] px-5">


            <div class="flex flex-col items-center">
                <h1 class="text-2xl font-bold tracking-tight lg:text-3xl">Log in</h1>
                <p class="mt-1 text-muted-foreground">Enter your email to log in or create account.</p>
            </div>

            <form class="mt-10" @submit="emailSubmit">
                <fieldset :disabled="isSubmitting" class="grid gap-4">
                    <UiVeeInput label="Email" type="email" name="email" placeholder="john_doe@example.com" />
                    <UiButton class="w-full" type="submit" text="Log in" />
                </fieldset>
            </form>
        </div>
    </div>
</template>

<script lang="ts" setup>
import {z} from 'zod';
import {useAuth} from "~/composables/useAuth";
const $auth = useAuth()

useSeoMeta({
    title: "Amulet - Log in",
    description: "Log in with your email or continue with Google, Facebook, or Github.",
});

const schema = z.object({
    email: z.string({ required_error: "Required" }).email("Please enter a valid email"),
});

const { handleSubmit, isSubmitting } = useForm({
    validationSchema: toTypedSchema(schema),
});

const emailSubmit = handleSubmit(async (values) => {
    useSonner.promise(new Promise(async (resolve) => {
        await $auth.sendCode(values.email)
        resolve(`Code sent! Check your inbox or spam for your login code.`)
    }), {
        loading: 'Sending login code to your email...',
        success: (d: any) => d,
        error: (d: any) => 'Unable to send login code to your email. :(',
    })
});
</script>
```

The logs:
```log
500
Cannot read properties of undefined (reading '_c')

at renderComponentRoot (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6408:16)
at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:732:28)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:664:12)
at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:86:10)
at _sfc_ssrRender (./node_modules/.js-transitions/TransitionSlide.vue:21:31)
at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:715:9)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:664:12)
at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:86:10)
at _sfc_ssrRender (./app/components/Ui/Vee/Input.js:145:31)
```

Runtime output:
```log
 WARN  [Vue warn]: Property "_self" was accessed during render but is not defined on instance. 
  at <TransitionSlide group="" tag="div" > 
  at <TransitionSlide group="" tag="div" > 
  at <Input label="Email" type="email" name="email"  ... > 
  at <Login onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/login" vnode= { __v_isVNode: true,
  __v_skip: true,
  type:
   { __name: 'login',
     setup: [Function (anonymous)],
     ssrRender: [Function: _sfc_ssrRender],
     __file: '/Users/administrator/Documents/WebStorm Projects/amulet/app/pages/login.vue' },
  props:
   { onVnodeUnmounted: [Function: onVnodeUnmounted],
     ref:
      RefImpl {
        dep: [Dep],
        __v_isRef: true,
        __v_isShallow: false,
        _rawValue: undefined,
        _value: undefined } },
  key: null,
  ref:
   { i:
      { uid: 112,
        vnode: [Object],
        type: [Object],
        parent: [Object],
        appContext: [Object],
        root: [Object],
        next: null,
        subTree: [Object],
        effect: null,
        update: null,
        job: null,
        scope: [EffectScope],
        render: [Function (anonymous)],
        proxy: [Object],
        exposed: null,
        exposeProxy: null,
        withProxy: null,
        provides: [Object <Complex prototype>],
        ids: [Array],
        accessCache: [Object: null prototype] {},
        renderCache: [],
        components: null,
        directives: null,
        propsOptions: [Array],
        emitsOptions: null,
        emit: [Function: bound emit],
        emitted: null,
        propsDefaults: [Object: null prototype] {},
        inheritAttrs: false,
        ctx: [Object],
        data: {},
        props: [Object],
        attrs: {},
        slots: [Object],
        refs: {},
        setupState: {},
        setupContext: [Object],
        suspense: null,
        suspenseId: 0,
        asyncDep: null,
        asyncResolved: false,
        isMounted: false,
        isUnmounted: false,
        isDeactivated: false,
        bc: null,
        c: null,
        bm: null,
        m: null,
        bu: null,
        u: null,
        um: null,
        bum: null,
        da: null,
        a: null,
        rtg: null,
        rtc: null,
        ec: null,
        sp: null },
     r:
      RefImpl {
        dep: [Dep],
        __v_isRef: true,
        __v_isShallow: false,
        _rawValue: undefined,
        _value: undefined },
     k: undefined,
     f: false },
  scopeId: null,
  slotScopeIds: null,
  children: null,
  component: null,
  suspense: null,
  ssContent: null,
  ssFallback: null,
  dirs: null,
  transition: null,
  el: null,
  anchor: null,
  target: null,
  targetStart: null,
  targetAnchor: null,
  staticCount: 0,
  shapeFlag: 4,
  patchFlag: 0,
  dynamicProps: null,
  dynamicChildren: null,
  appContext: null,
  ctx:
   <ref *1> {
     uid: 112,
     vnode:
      { __v_isVNode: true,
        __v_skip: true,
        type: [Object],
        props: [Object],
        key: null,
        ref: null,
        scopeId: null,
        slotScopeIds: null,
        children: [Object],
        component: [Circular *1],
        suspense: null,
        ssContent: null,
        ssFallback: null,
        dirs: null,
        transition: null,
        el: null,
        anchor: null,
        target: null,
        targetStart: null,
        targetAnchor: null,
        staticCount: 0,
        shapeFlag: 36,
        patchFlag: 0,
        dynamicProps: null,
        dynamicChildren: null,
        appContext: null,
        ctx: [Object] },
     type:
      { name: 'RouterView',
        inheritAttrs: false,
        props: [Object],
        compatConfig: [Object],
        setup: [Function: setup] },
     parent:
      { uid: 111,
        vnode: [Object],
        type: [Object],
        parent: [Object],
        appContext: [Object],
        root: [Object],
        next: null,
        subTree: [Object],
        effect: null,
        update: null,
        job: null,
        scope: [EffectScope],
        render: [Function (anonymous)],
        proxy: [Object],
        exposed: [Object],
        exposeProxy: null,
        withProxy: null,
        provides: [Object <Complex prototype>],
        ids: [Array],
        accessCache: [Object: null prototype] {},
        renderCache: [],
        components: null,
        directives: null,
        propsOptions: [Array],
        emitsOptions: null,
        emit: [Function: bound emit],
        emitted: null,
        propsDefaults: [Object: null prototype] {},
        inheritAttrs: false,
        ctx: [Object],
        data: {},
        props: [Object],
        attrs: {},
        slots: {},
        refs: {},
        setupState: {},
        setupContext: [Object],
        suspense: null,
        suspenseId: 0,
        asyncDep: null,
        asyncResolved: false,
        isMounted: false,
        isUnmounted: false,
        isDeactivated: false,
        bc: null,
        c: null,
        bm: null,
        m: null,
        bu: null,
        u: null,
        um: null,
        bum: null,
        da: null,
        a: null,
        rtg: null,
        rtc: null,
        ec: null,
        sp: null },
     appContext:
      { app: [Object],
        config: [Object],
        mixins: [],
        components: [Object],
        directives: {},
        provides: [Object: null prototype],
        optionsCache: [WeakMap],
        propsCache: [WeakMap],
        emitsCache: [WeakMap] },
     root:
      <ref *2> {
        uid: 106,
        vnode: [Object],
        type: [Object],
        parent: null,
        appContext: [Object],
        root: [Circular *2],
        next: null,
        subTree: null,
        effect: null,
        update: null,
        job: null,
        scope: [EffectScope],
        render: [Function: NOOP],
        proxy: {},
        exposed: {},
        exposeProxy: null,
        withProxy: null,
        provides: [Object <Complex prototype>],
        ids: [Array],
        accessCache: [Object: null prototype] {},
        renderCache: [],
        components: null,
        directives: null,
        propsOptions: [],
        emitsOptions: null,
        emit: [Function: bound emit],
        emitted: null,
        propsDefaults: [Object: null prototype] {},
        inheritAttrs: undefined,
        ctx: {},
        data: {},
        props: {},
        attrs: {},
        slots: {},
        refs: {},
        setupState: [Object],
        setupContext: [Object],
        suspense: null,
        suspenseId: 0,
        asyncDep: null,
        asyncResolved: false,
        isMounted: false,
        isUnmounted: false,
        isDeactivated: false,
        bc: null,
        c: null,
        bm: null,
        m: null,
        bu: null,
        u: null,
        um: null,
        bum: null,
        da: null,
        a: null,
        rtg: null,
        rtc: null,
        ec: [Array],
        sp: null,
        devtoolsRawSetupState: [Object] },
     next: null,
     subTree:
      { __v_isVNode: true,
        __v_skip: true,
        type: [Object],
        props: [Object],
        key: null,
        ref: null,
        scopeId: null,
        slotScopeIds: null,
        children: [Object],
        component: null,
        suspense: null,
        ssContent: [Object],
        ssFallback: [Object],
        dirs: null,
        transition: null,
        el: null,
        anchor: null,
        target: null,
        targetStart: null,
        targetAnchor: null,
        staticCount: 0,
        shapeFlag: 160,
        patchFlag: 0,
        dynamicProps: null,
        dynamicChildren: null,
        appContext: null,
        ctx: [Object] },
     effect: null,
     update: null,
     job: null,
     scope:
      EffectScope {
        detached: true,
        _active: true,
        effects: [],
        cleanups: [],
        _isPaused: false,
        parent: undefined },
     render: [Function (anonymous)],
     proxy: { name: [Getter/Setter], route: [Getter/Setter] },
     exposed: null,
     exposeProxy: null,
     withProxy: null,
     provides:
      Object <Object <Complex prototype>> {
        [Symbol(router view depth)]: [ComputedRefImpl],
        [Symbol(router view location matched)]: [ComputedRefImpl],
        [Symbol(router view location)]: [ComputedRefImpl] },
     ids: [ '', 0, 0 ],
     accessCache: [Object: null prototype] {},
     renderCache: [],
     components: null,
     directives: null,
     propsOptions: [ [Object], [Array] ],
     emitsOptions: null,
     emit: [Function: bound emit],
     emitted: null,
     propsDefaults: [Object: null prototype] {},
     inheritAttrs: false,
     ctx: { name: [Getter/Setter], route: [Getter/Setter] },
     data: {},
     props: { route: undefined, name: 'default' },
     attrs: {},
     slots: { default: [Function] },
     refs: {},
     setupState: {},
     setupContext: { attrs: [Getter], slots: [Getter], emit: [Getter], expose: [Function: expose] },
     suspense: null,
     suspenseId: 0,
     asyncDep: null,
     asyncResolved: false,
     isMounted: false,
     isUnmounted: false,
     isDeactivated: false,
     bc: null,
     c: null,
     bm: null,
     m: null,
     bu: null,
     u: null,
     um: null,
     bum: null,
     da: null,
     a: null,
     rtg: null,
     rtc: null,
     ec: null,
     sp: null } } route= { fullPath: '/login',
  hash: '',
  query: {},
  name: 'login',
  path: '/login',
  params: {},
  matched:
   [ { path: '/login',
       redirect: undefined,
       name: 'login',
       meta: {},
       aliasOf: undefined,
       beforeEnter: undefined,
       props: [Object],
       children: [],
       instances: {},
       leaveGuards: Set(0) {},
       updateGuards: Set(0) {},
       enterCallbacks: {},
       components: [Object] } ],
  meta: {},
  redirectedFrom: undefined,
  href: '/login' }  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>
```

**Comment by Type-32** [comment]
I think I missed some steps in installation. This happens when a Transition related tag was used.

**Comment by BayBreezy** [comment]
Hey @Type-32 That bug came from a dependency. 
Me and the author of the @morev/vue-transition made some changes to the package and it negatively affected Nuxt. you can see some more here: https://github.com/MorevM/vue-transitions/issues/268

It got sorted out shortly after. But thanks for reporting 👍🏽

**Comment by Type-32** [comment]
My workaround was to import the components manually. If not, update to the latest dependencies and import it again.

**Comment by BayBreezy** [comment]
Try updating the transition dependency that the input uses. 
There was a bug in an older version that me and the author ended up fixing

**Comment by davidreyg** [comment]
My bad. 
I'm using bun. so I just realized in the  [docs](https://github.com/MorevM/vue-transitions/tree/master?tab=readme-ov-file#using-bun) that i needed to add this to mi package.json and reinstall with `bun install` :)
```
{
  "trustedDependencies": ["@morev/vue-transitions"]
}

```

Anyway. thanks for helping.

**Comment by BayBreezy** [comment]
Oh.. Another thing to look out for. 
Thanks for sharing the solution.
As it relates to the zod vs yup for validation.... I use yup in the real world. I just added zod because of the hype around it. I am not a big fan of it 🤷🏽‍♂️
